### ISSUE TITLE
socat listen port 

### ISSUE THREAD

**Issue by RangerRU** [aleskxyz/warp-svc#3]
Hello
Can you change the socat port from 1080 to any other that is not used as standard proxy ports?

**Comment by aleskxyz** [comment]
Hi
What is your use case?
You can change the public port in docker run or docker compose.
For example use this:
9999:1080

**Comment by RangerRU** [comment]
I'm using XRay (Marzban, 3x-ui), port 1080 is used for the shadowsocks protocol (standard port)

> {
>       "tag": "Shadowsocks TCP",
>       "listen": "0.0.0.0",
>       "port": 1080,
>       "protocol": "shadowsocks",
>       "settings": {
>         "clients": [],
>         "network": "tcp,udp"
> }

fro entrypoint.sh:

> socat tcp-listen:1080,reuseaddr,fork tcp:localhost:40000 &

netstat -plnut
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      316054/socat

**Comment by aleskxyz** [comment]
create a directory:
```
mkdir warp
cd warp
```
create a `docker-compose.yml` file with this content:
```
version: "3"
services:
  warp:
    image: aleskxyz/warp-svc:latest
    environment:
      WARP_LICENSE: xxxxxxxx-xxxxxxxx-xxxxxxxx
    ports:
    - 127.0.0.1:2323:1080
    restart: always
    volumes:
    - ./warp:/var/lib/cloudflare-warp
```
run docker compose:
```
docker compose up -d
```
Now you can use socks on 127.0.0.1:2323 and use it in xray
